### ISSUE TITLE
Canvas not rendering shapes in Voila

### ISSUE THREAD

**Issue by Voranto** [jupyter-widgets-contrib/ipycanvas#342]
Just as the title says, im trying to render the canvas I'm using in Jupyter Notebook, it works perfectly fine, with all the drawing functions I've added. But when trying to convert to Voila, the canvas appears blank and unresponsive, and even if i try to render static shapes, doesn't work.

![image](https://github.com/jupyter-widgets-contrib/ipycanvas/assets/93982008/a7e0bfff-5ffd-4766-9f82-1a9698cac8d9)
This is in jupyter notebook

-------------------------------
This is in Voila
![image](https://github.com/jupyter-widgets-contrib/ipycanvas/assets/93982008/2fa4c950-ad93-4226-88e4-63a1f2dcc5e9)

I have tried the advice in the documentation, but even when using the following code, it doesn't work
![image](https://github.com/jupyter-widgets-contrib/ipycanvas/assets/93982008/c5273f42-c04d-402e-a11d-5c40467ee4db)

Ive tried everything...

**Comment by martinRenou** [comment]
Answered in https://github.com/voila-dashboards/voila/issues/1447
